### ISSUE TITLE
怎么判断已经执行完毕了

### ISSUE THREAD

**Issue by qiaocuixinzhiweini** [coffeedeveloper/typing.js#2]
RT，执行完毕之后需要调用其它函数，如何写这个回调

**Comment by coffeedeveloper** [comment]
目前不支持播放后回调，晚点我有时间（这两天）加上🤔

**Comment by qiaocuixinzhiweini** [comment]
恩，我今天尝试添加没有成功，时间所限，用了setTimeout进行冷处理，期待你添加这个功能，还有可能暂停功能也会很实用的

**Comment by coffeedeveloper** [comment]
你在初始化的时候传入一个 done: function() {} 就可以了。具体你可以看文档。
