### ISSUE TITLE
如何加快换行后开始打印的速度？

### ISSUE THREAD

**Issue by lydasia** [coffeedeveloper/typing.js#5]
如何加快换行后开始打印的速度？对我来说开始打印新的一行要等的时间有些长了，没有找到在哪里调整这个速度。

感谢作者！

**Comment by coffeedeveloper** [comment]
目前是没有参数来加快换行的速度的，会行程慢的原因是因为你的参照区域的代码里面有换行例如：
```
<p>
<span>111</span>
<span>222</span>
</p>
```
这种`tag`之间的空隙，实际上也是会产生一个文本的textnode的。所以如果你喜欢换行速度加快的话，建议你压缩一下参照区域的dom结构，压缩成：
```
<p><span>111</span></p>
```
这种打印速度就会大大加快了。
实际上这种textnode如果在程序上去优化掉的话，也会造成别的影响，比如一段话之间的空隙，所以还是建议你从执行代码的角度去优化，希望能帮助到你。

**Comment by lydasia** [comment]
@coffeedeveloper 我用的是<br>标签，也很紧凑，是前面缩进的问题。多谢！
